### ISSUE TITLE
documentation/model.png

### ISSUE THREAD

**Issue by beutlich** [Kvixen/Simulix#16]
What is the purpose of adding the model.png to the /documentation of the FMU? The image is just a 6KB PNG header and not a valid file. If it would work, I also wonder if it is necessary to add a such default file.

**Comment by Kvixen** [comment]
When I was introduced to FMI and started writing the software all my co-workers who was questioned about the model.png just said [thats how things are done around here.](https://i.stack.imgur.com/MyQki.jpg) For some reason, even with the information from the FMI docs, I just thought it was a standard. Do you propose the removal of the image all together or possibly another default one?
