### ISSUE TITLE
Get Simulix listed at the official FMI tools site

### ISSUE THREAD

**Issue by tbeu** [Kvixen/Simulix#19]
Do you fancy to get Simulix officially listed at https://fmi-standard.org/tools/? Please consider the [contribution guideline](https://github.com/modelica/fmi-standard.org/blob/master/CONTRIBUTING.md#updating-the-tools-list) for you PR.

**Comment by beutlich** [comment]
Any feedback?

**Comment by Kvixen** [comment]
Pull request added to fmi-standard.org
