### ISSUE TITLE
Fmu which created by simulix was exported to maplesim2018 make an error

### ISSUE THREAD

**Issue by qilianshanlgz** [Kvixen/Simulix#25]
Thank you for your toolbox . When I exported FMU file which was created by Simulix to maplesim2018 was not successful. Error showed that ‘  'initial should not be specified for causality of type 'input' or ‘independent'  ' MATLAB 2017B was used to created the ZIP flie.
![image](https://user-images.githubusercontent.com/38285844/53341111-a11bef80-3945-11e9-94a4-6a5869783889.png)

**Comment by Kvixen** [comment]
This should be fixed in commit d1540a3669d54815f9c63096e62245e9442597cb.
