### ISSUE TITLE
Empty /fmiModelDescription/ModelStructure/Derivatives and InitialUnknowns

### ISSUE THREAD

**Issue by tkorvola** [Kvixen/Simulix#27]
Simulix produces empty `Derivatives` and `InitialUnknowns` elements in the model description. The FMI 2.0 schema allows these elements to be absent but not empty. Removing their output from `Simulix_exemain_template.c` appears to suffice as a fix.

**Software (please complete the following information):**
 - Simulix version 1.0
 - Matlab version R2018b

**Comment by Kvixen** [comment]
I can't seem to find this mentioned anywhere in the specification. If you have the section in mind, please refer me to it.

**Comment by tkorvola** [comment]
I am referring to the XML schema fmi2ModelDescription.xsd included in the complete FMI 2.0 specification package published at fmi-standard.org.
