### ISSUE TITLE
Destroys current working directory

### ISSUE THREAD

**Issue by tkorvola** [Kvixen/Simulix#31]
The argument of the `-p` option is destroyed with `shutil.rmtree`. It defaults to the current working directory, which is likely to cause extremely nasty surprises.

This appears to have got botched in 923a7ef43300a35735c24a8e6af3abac3872f6ac.

**Comment by Kvixen** [comment]
As this issue didn't exist before 923a7ef43300a35735c24a8e6af3abac3872f6ac, simply reverting the changes will also correct the logic for the temp folder removing and removes the issue.
