### ISSUE TITLE
Support of release build

### ISSUE THREAD

**Issue by beutlich** [Kvixen/Simulix#4]
Is there any option or orkaround to build a non-debug configuration. Currently the binary is always (cross-)compiled as debug configuration.

**Comment by Kvixen** [comment]
Added a branch called debug-flag with a --DEBUG-BUILD flag. Now default is release. Is this what you had in mind? I'm sadly not able to test it out, which is why I created a new branch. Please try it out if you can and close the issue if it's resolved. Otherwise, please expand on the issue.

**Comment by beutlich** [comment]
Works as expected. Thank you. Can you please merge to master?

**Comment by Kvixen** [comment]
Branch is merged with master.
