### ISSUE TITLE
Rename exception if FMU already exists

### ISSUE THREAD

**Issue by beutlich** [Kvixen/Simulix#8]
There is a `FileExistsError` during rename if the FMU file already exists

```sh
Traceback (most recent call last):
  File "Simulix.py", line 80, in <module>
    main()
  File "Simulix.py", line 56, in main
    pack_fmu(args.p, path.join(args.p, environ['SIMX_MODEL_NAME']), environ['SIMX_MODEL_NAME'])
  File "D:\Projects\Simulix\pack.py", line 9, in main
    rename(path.join(dst, name + '.zip'), name + ".fmu")
FileExistsError: [WinError 183] Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist: 'Example.fmu'
```

**Comment by Kvixen** [comment]
Added improved error handling in pack.py. If the archive name + (.zip|.fmu) now exist, I generate a uuid and add it to the name of the archive. This was the most effective method I could think of. Produces filenames like modelname4316a40e1a424b07a374b96db62fa244.fmu if the archive modelname already exist.
